apiVersion: v1
data:
  frontend.jsonnet: |
    local common = import 'common.libsonnet';

    {
      blobstore: common.blobstore,
      httpListenAddress: common.httpListenAddress,
      grpcServers: [{
        listenAddresses: [':8989'],
        authenticationPolicy: { allow: {} },
      }],
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
    }
kind: ConfigMap
metadata:
  name: frontend
  namespace: buildbarn
